### ISSUE TITLE
How to change fpn backbone structure to mobilenetv1 other than ["resnet50", "resnet101"]

### ISSUE THREAD

**Issue by pylearndl** [edouardlp/Mask-RCNN-CoreML#4]
I successfully trained MaskRCNN model with BACKBONE "mobilenetv1". H5 model file is about 83mb. Now, I am trying to convert .h5 to .mlmodel with Mask-RCNN-CoreML. I got error it can only support backbone resnet50 or resnet101. Is there any way I convert with mobilenetv1 backbone structure?

```
$ swift run maskrcnn convert test
Converting 'test' model to CoreML.
Traceback (most recent call last):
  File "./task.py", line 173, in <module>
    mask_rcnn_model, classifier_model, mask_model, anchors = model.get_trained_keras_models()
  File "/usr/local/lib/python3.6/site-packages/maskrcnn/model.py", line 200, in get_trained_keras_models
    anchors = self._build_keras_models(environment="coreml")
  File "/usr/local/lib/python3.6/site-packages/maskrcnn/model.py", line 231, in _build_keras_models
    return _build_keras_models(self.config, environment)
  File "/usr/local/lib/python3.6/site-packages/maskrcnn/model.py", line 64, in _build_keras_models
    P2, P3, P4, P5, P6 = backbone.build(environment=environment)
  File "/usr/local/lib/python3.6/site-packages/maskrcnn/subgraphs/fpn_backbone_graph.py", line 18, in build
    C1, C2, C3, C4, C5 = resnet_graph(self.input_tensor, architecture=self.architecture, stage5=True, train_bn=False)
  File "/usr/local/lib/python3.6/site-packages/maskrcnn/subgraphs/fpn_backbone_graph.py", line 130, in resnet_graph
    assert architecture in ["resnet50", "resnet101"]
AssertionError
```

**Comment by pylearndl** [comment]
Solved it.
I have added code for Mobilenet V1 Graph, and Mobilenet V2 Graph in fun_backbone_graph.py on the docker container. Make sure to use `keras.layers.BatchNormalization`, instead of `class BatchNorm(KL.BatchNormalization):` Because if you use class it will give Custom Layers error when importing converted mlmodel in Xcode project.

**Comment by Darko28** [comment]
@pylearndl Glad to see someone changing the backbone to MobileNet!
  I was wondering the performance after you changed the backbone to MobileNet, like the accuracy and the detection rate. Is it faster than the original one?

Thanks a lot ;)

**Comment by pylearndl** [comment]
I tranined maskrcnn model for only one class to detect segmentation. It does perform well enough. Also maskrcnn model is only 24mb with backbone mobilenetv1. It is light weight.
But, I'm still trying to make it perfect as much as I could. I'll also try back one mobilenetv2 to see the difference with v1.
As far as detection of my own class and segmentation is concerns, it takes about less than 2 seconds in iphoneX.

**Comment by Darko28** [comment]
@pylearndl Thanks for the reply. I'd like to keep up with your work )

I see edouardlp is also planning to try a mobile-optimized backbone. And to be honest, implementing MobileNetV2 as the backbone is also part of my plan in the future.    Also, I would like to know if you are planning on training the model using COCO dataset. Maybe it will affect the performance?  Cuz I'm currently using an iPhone 7p for testing, so no way I can take less than 2 seconds now.

Very much appreciated.

**Comment by pylearndl** [comment]
@DarkoBomer Coco is huge dataset. I believe it will effect the performance if I use coco present dataset to train the model and try converted mlmodel with iphonex. 
I trained my model with fairly small dataset with only 160 train images and with 70 validation images and annoations.

**Comment by Darko28** [comment]
@pylearndl Thanks!

**Comment by alwc** [comment]
Hi @pylearndl  , I'm curious how much memory does your MobileNetV2 + Mask-RCNN use on your iPhone X when doing inference?

**Comment by pylearndl** [comment]
> Hi @pylearndl , I'm curious how much memory does your MobileNetV2 + Mask-RCNN use on your iPhone X when doing inference?

<img width="1417" alt="Screen Shot 2019-06-04 at 10 39 26" src="https://user-images.githubusercontent.com/46265022/58870013-3f42f280-86b7-11e9-893d-276029089fb7.png">

MobileNetV2 + Mask-RCNN takes about 2-3 second to process one image file. iPhoneX memory usage went upto 1.46 gb while processing to detect masks. I have attached screenshot for reference.
